use_frameworks!

target 'ALWStarComment_Example' do
  pod 'ALWStarComment', :path => '../'

  target 'ALWStarComment_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
